spring:
  devtools:
    livereload:
      port: 35730
  application:
    name: CONFIG
  profiles:
    active: native
    include: @env@
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config/@env@