spring:
  devtools:
    livereload:
      port: 35730
  application:
    name: CONFIG
  profiles:
    active: native
    include: @env@
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config/@env@

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
    app-group-name: 配置中心
    appname: ${spring.application.name}

