spring:
  devtools:
    livereload:
      port: 35732
  application:
    name: USER

server:
  port: 8764

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
    app-group-name: 用户服务
    appname: ${spring.application.name}