app:
  foo: local-application-task

server:
  port: 80

spring:
  application:
    name: cloud-task
  datasource:
    name: 主库
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.97.215.198:3306/backend?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
    username: root
    password: ENC(0pyrPolbV/HFj5lXqGuo5kJaPXRw95nu7cJOyHk9xFY=)
  redis:
    host: ENC(8MyBY/XN0vuPn8xmnFm2RHFMoUU3eLRR)
    port: 6379
    password: ENC(tASKqBx0gzWsXpfREzVYoQdCFpDw7wCS)
