foo: local-application-task

server:
  port: 8764

spring:
  application:
    name: cloud-task
  datasource:
    name: 主库
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/backend?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
    username: root
    password: Chen1436863821.
  redis:
    host: 127.0.0.1
    port: 6379
    password: Chen1436863821.
