server:
  port: 80

spring:
  application:
    name: cloud-manage
  datasource:
    name: 主库
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.97.215.198:3306/backend?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
    username: root
    password: mysql.aliyun.chenfangming.com:3306
  redis:
    host: redis.aliyun.chenfangming.com
    port: 6379
    password: redis.aliyun.chenfangming.com:6379

app:
  qq:
    app-id: 00101577560
    app-key: b74b3fdad268cd6b4ac9dbba278174eb
    oauth-server-url: https://graph.qq.com/
    call-back-url: http://cloud.chenfangming.com/callback/qq
