foo: DEV环境

server:
  port: 8764

spring:
  application:
    name: USER
  datasource:
    name: primary
    username: root
    password: Chen1436863821.
    url: jdbc:mysql://127.0.0.1:3306/backend?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver