server:
  port: 8761

spring:
  application:
    name: eureka

eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
  server:
    enable-self-preservation: false
  client:
    fetch-registry: false
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka