#  Server容器配置
server:
  port: 8761

eureka:
  instance:
    hostname: 127.0.0.1
  server:
    enable-self-preservation: false
  client:
    fetch-registry: false
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

